python src/main_mlm.py \
--data_dir ./data \
--results_dir ./ \
--trained_dir ./ \
--data amazon_fashion \
--device 0 \
--batch_size 1 \
--lr 3e-6 \
--n_epochs 1 \
--lambda_a 1e-1 \
--lambda_w 1e-1 \
--social_dim 50 \
--gnn GAT